# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-06-24 07:17
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190624_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='uuid',
            field=models.CharField(default=uuid.UUID('18b74734-5d75-40cc-b232-4441f3e0f6b7'), max_length=50, verbose_name='唯一标识符'),
        ),
    ]
