# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-07-11 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190711_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='imagecontent',
            field=models.FileField(default='', upload_to='faceimg/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='uuid',
            field=models.CharField(default=uuid.UUID('f32e366b-53f5-4143-afee-0d39e9d1e76c'), max_length=50, verbose_name='唯一标识符'),
        ),
    ]
