# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-07-26 06:46
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190726_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='uuid',
            field=models.CharField(default=uuid.UUID('eba7a6b5-d47b-4308-92ed-d033de552013'), max_length=50, verbose_name='唯一标识符'),
        ),
    ]
