# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-07-27 08:24
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20190726_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='uuid',
            field=models.CharField(default=uuid.UUID('ef399a15-a4a8-4bad-b1b4-0a64c640e4d4'), max_length=50, verbose_name='唯一标识符'),
        ),
    ]
