# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-07-27 08:26
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20190727_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='uuid',
            field=models.CharField(default=uuid.UUID('e93bbba3-c9b9-41ec-89fd-4c027f5f0967'), max_length=50, verbose_name='唯一标识符'),
        ),
    ]
