# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-07-27 09:58
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20190727_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='uuid',
            field=models.CharField(default=uuid.UUID('cf3ed2cf-cec8-4145-bcde-a713b7c271c8'), max_length=50, verbose_name='唯一标识符'),
        ),
    ]
