# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-08-01 11:28
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20190727_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='add_time',
            field=models.DateField(default='2019-08-01 11:28:12', verbose_name='登录时间'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='uuid',
            field=models.CharField(default=uuid.UUID('499fe7e3-4446-4466-bed4-47a09a1d570f'), max_length=50, verbose_name='唯一标识符'),
        ),
    ]
