# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-08-01 11:29
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20190801_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='uuid',
            field=models.CharField(default=uuid.UUID('7341b808-b404-41cd-953e-549924b2b365'), max_length=50, verbose_name='唯一标识符'),
        ),
    ]
