# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-06-24 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20190624_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='star',
            field=models.FloatField(verbose_name='推荐指数'),
        ),
    ]
