# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-06-24 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20190624_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='play_nums',
            field=models.CharField(max_length=64, verbose_name='播放量'),
        ),
    ]
