# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-07-26 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20190624_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='play_nums',
            field=models.IntegerField(max_length=64, verbose_name='播放量'),
        ),
    ]
