# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-07-26 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_auto_20190726_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='play_nums',
            field=models.IntegerField(verbose_name='播放量'),
        ),
    ]
