# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-07-27 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_auto_20190726_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='play_id',
            field=models.CharField(default=2, max_length=255, verbose_name='电影ID'),
            preserve_default=False,
        ),
    ]
