# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-07-27 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_movie_play_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='play_id',
            field=models.CharField(default='', max_length=255, verbose_name='电影ID'),
        ),
    ]
